[profile.default]
src = "contracts"
out = "out"
libs = ["node_modules"]
optimizer = true
optimizer_runs = 1000
solc_version = "0.8.17"

remappings = [
    "@openzeppelin/=node_modules/@openzeppelin/",
    "@keep-network/=node_modules/@keep-network/",
    "@thesis/=node_modules/@thesis/",
    "@threshold-network/=node_modules/@threshold-network/",
]

# Skip test files that need forge-std
test = "test-foundry"

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/qyC3cd-nNqHUYf6EbhUPp"

[etherscan]
mainnet = { key = "NH5KEXMFZ2Y5RXM4PFEZR7RW6JD9VZWAH5" }
